### PR TITLE
Issue 87

### PR DESCRIPTION
**Pull request by peoray**
I added an additional message to the welcome text for new users that is triggered by the join event. This is in reference to the [issue created here](https://github.com/codebuddies/greetbot/issues/87).

Below is a screenshot of the addition made:
fixed

### CODE REVIEW

**Comment by BethanyG** [comment]
WHOO HOOO!  Congratulations @peoray!!
@lpatmo  & @wuworkshop -- is this what you had in mind for the message, or does it need re-wording?

@stain88 or @angelocordon - can one of you review these changes - I'm a bit too close to them at the moment.

Thanks so much everyone!

**Comment by lpatmo** [comment]
Sorry I just saw this. Thanks @peoray for your work!

**Review by angelocordon — APPROVED** [review]
LGTM 👍

**Comment by peoray** [comment]
Thanks guys, this means a lot!

**Pull request merged**
